inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

# This is required in app/services/pafs_core/download/base.rb
# but adding a disable directive there causes rubocop to complain
# about an unnecessary disable directive, so disabling it here instead.
Style/RedundantInitialize:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    # let! it be for entities which need to exist in the database without being referenced in the spec
    - "spec/services/pafs_core/project_service_spec.rb"
    - "spec/services/pafs_core/change_project_area_service_spec.rb"