language: ruby
cache: bundler
rvm:
- 2.3.0
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libproj-dev
  - sudo apt-get install -y libffi-dev
  - git config --global user.name "Travis Test"
  - git config --global user.email travis@example.com
script:
  - >-
    bundle exec rake spec

services:
  - postgresql
notifications:
  slack:
    secure: cTsubHjA23lK7Cgt2LhXyxV65UlA7hoaLRWSpXpYm6RNkqU9T8NZuSBnQj2OiDlzUc8jYn+m5Q/DLGmIhiA0jR5+Z24rHcUsfrd0t3czNCui0kajvimt2qbK5avV1jzEsVOBZVJ4B7LFtU0vwvGmGFDpP6jW8YS/MekABla9Y8Sf0TwVg6NmIhJm3PXYjrYyYHK+QADwg0JIQDiuxsvMvMLsf3j3Xk/cqVxxe3SuiX84UOvPvy2g7j520utuIPo6l7V6O1RcPjam98A7omMNrDc7VDHKj6BsLHVEVQ/WXjsLd6hvtelval7/F2QNVt9ySNd11arIwc2ga5yO1JkTbO1I5J58kszGUwJhRwmCY0kukvcpcbcoFTYzvR9ILGZ6P0RWEEAby5yOGdsiRqtI1eFEU4vutjxUOCoUOSZ8BCPlLdxM8sRyjzJ5HDeZhG6NNH6V9KKfrKIPP/vWBoVzMhRatg9k56pB9/d/F2K79e24kVPkWaASrImHE37Ne+uM8+1b0eYn4S56HQz9VTuYuAq3X1aiYrbep5AQ/p4LPi4RSS2janHixIrxuFKggLH8dJjnaDvSfZ6iopsaCZn06IZE0Cz0TVS4VOkwSBhjBnWWNN6bPVNJz665YjfxC/cPSZBVO58m+qRRB05El51x/F2UvIYaii6Tjgl22AkOArA=
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 6329f07963b904dfc32beac2596e2aa3b1a980a2953de6613ec1bbc78c827d5a
