default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  post: 5432
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: pafs_core_dummy_development

test:
  <<: *default
  database: pafs_core_dummy_test
  host: 127.0.0.1
  username: postgres
  password: postgres

production:
  <<: *default
  database: pafs_core_dummy_production